apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
  labels:
    app: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-crud-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-crud-deployment
    spec:
      containers:
        - name: springboot
          image: narimannasser/backrepo:backimage
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: USERNAME
              value: root

            - name: PASSWORD
              value: root

            - name: URL
              value: mysql

            - name: PORT
              value: '8080'
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
